#!/bin/bash

git config --global alias.sube '!git-submodule-ext'
git config --global alias.sfe '!git sube foreach'
git config --global alias.sfer '!git sfe -r'
git config --global alias.tsfe '!git sfe -t'
git config --global alias.tsfep '!git sfe -t -p'
git config --global alias.tsfer '!git sfe -t -r'
git config --global alias.tsferp '!git sfe -t -r -p'