#!/bin/bash

# Too lazy for /bin/sh
bin="$(basename $0)"

usage()
{
	echo "$bin [--clean] [--link] DEST"
	exit $1
}

clean=
link=
while test $# -gt 0
do
	case $1 in
		--clean)
			clean=1
			;;
		--link)
			link=1
			;;
		-h|--help)
			usage 0
			;;
		*)
			break
			;;
	esac
	shift
done

test $# -eq 0 && echo "Need to supply directory (absolute path) to put this stuff in." && usage 1
dir=$1
shift

path=$(dirname $BASH_SOURCE)
cd $path

linkerade()
{
	new=$(basename $1 .sh)
	src=~+/$1
	dest=$dir/$new
	if test -e "$dest" -a -n "$clean"
	then
		echo -e "\tRemoving $dest"
		rm $dest
	fi
	if test -z "$link"
	then
		echo "Copying $src -> $dest"
		cp $src $dest
	else
		echo "Linking $src -> $dest"
		ln -s $src $dest
	fi
}

if test $# -eq 0
then
	scripts=$(dir *.sh)
else
	scripts=$@
fi

for script in $scripts
do
	linkerade $script
done
