#!/bin/bash
set -e -u

# Is there a script like this already?

# Too lazy for /bin/sh
bin="$(basename $0)"
usage()
{
	echo "$bin [--no-clean] [--link] [-u | --uninstall] DEST"
	exit $1
}

clean=1
link=
uninstall=
while test $# -gt 0
do
	case $1 in
		--no-clean)
			clean=
			;;
		--link)
			link=1
			;;
		-u|--uninstall)
			uninstall=1
			;;
		-h|--help)
			usage 0
			;;
		*)
			break
			;;
	esac
	shift
done

if test $# -eq 0
then
	echo "Need to supply directory (absolute path) to put this stuff in."
	usage 1
fi
dir=$1
shift

path=$(dirname $BASH_SOURCE)
cd $path

linkerade()
{
	new=$(basename $1 .sh)
	src=~+/$1
	dest=$dir/$new
	if test \( -e "$dest" -o -L "$dest" \) -a \( -n "$uninstall" -o -n "$clean" \)
	then
		echo -e "Removing $dest"
		rm $dest
	fi
	if test -z "$uninstall"
	then
		if test -z "$link"
		then
			echo "Copying $src -> $dest"
			cp $src $dest
		else
			echo "Linking $src -> $dest"
			ln -s $src $dest
		fi
	fi
}

if test $# -eq 0
then
	scripts=$(dir *.sh)
else
	scripts=$@
fi

for script in $scripts
do
	linkerade $script
done